jwt:
  token:
    secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: zzalu-buket
    credentials:
      access-key: AKIAXEUXRPXD3GDITUSE
      secret-key: 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
    stack:
      auto: false
sp: ''
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: moona0222@hufs.ac.kr
    password: 5525dnflwlq!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3307/ZZALU?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
  kafka:
    bootstrap-servers: localhost:9092
  #    consumer:
  #      auto-offset-reset: earliest
  #      bootstrap-servers: localhost:9092
  #      group-id: foo
  #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  #      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer
  #    producer:
  #      bootstrap-servers: localhost:9092
  #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: '123456'

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false


## properties
##h2 console ??? ? ?? ??
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
##h2 db ??
#spring.datasource.url=jdbc:h2:~/test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#
##hibernate ??
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.hibernate.ddl-auto=create